version: '3.12'

services:
  ceaser-cipher-api:
    build: .
    ports:
      - "5000:5000"
    volumes:
      - .:/app
    environment:
      - FLASK_APP=app.py
      - FLASK_ENV=development
      - FLASK_RUN_HOST=0.0.0.0
    command: flask run

networks:
  default:
    external:
      name: ceaser-cipher-network